### PR TITLE
Update deps

### PR DESCRIPTION
**Pull request by the-simian**
there are 4 main changes.

1. add babel-runtime, which fixes the build errors
2. update some packages to the latest, such as redux, redux-router, lodash, etc
3. since lodash is update, the uniqueId refernce also required update
4. a .gitignore was not in the project to ignore node modules, so I added one.

### CODE REVIEW

**Comment by the-simian** [comment]
resolves https://github.com/ipselon/material-ui-prepack/issues/5

**Comment by ipselon** [comment]
there are some changes which are not acceptable for this moment because Structor generates the source code while exporting a project with react-router v 1.0.0. This can be done only after new version of Structor. 
What exactly did fix your problem?

**Comment by the-simian** [comment]
the main change was the babel-runtime dependency was missing in the project, I commented more in the other thread, so we can move to there

**Comment by ipselon** [comment]
Perfect, if you don't mind please change the PR with excluded changes to router.
The React Router is here only for building and running the exported code from Structor. And router is used internally by Structor inself, but this is the dep of Structor. So, if you don't want to use router of this version you can update in your local project. Additionaly, I'm preparing a new version of Structor where new version of router will be, but this will be done till the end of this month because there will be a lot of changes.

As for

**Comment by the-simian** [comment]
Ok, that's no problem. let me make the change, make sure it build, and then I'll resubmit a PR. Thank you for the fast response. I'm working on this now.

**Comment by Bartekus** [comment]
I've just tested this agains the newest structor and can confirm that everything is 100%; all the packages are up to their most current version and overall there are no observable glitches or issues that were notice by me during the check. The version that I've tested was the one with 2.x.x react-router as that's the one I intend to use on a broader scale for my project, as such I'll keep an eye for any potential unnoticed problem and report back accordingly.

**Comment by the-simian** [comment]
@Bartekus and @ipselon , ok I did the changes you requested, in this PR the changes to router and history are reverted. Everything else is up to date.

I did make the changes we discussed to the .gitignore file.

I did want to point out one last thing: most of the files, as you know are generated. this worked 100% for me, but I did not include the regenerated files after actually running this. I will also add, that another route: Tabs.js gets spit out into the routes folder. I did not include this either, since it gets included the first tiem you click export and I wanted to keep the PR simple!

Thank you again. I can't wait for you to pull this into your project :)

**Comment by ipselon** [comment]
@the-simian thank you. Merging...

**Pull request merged**
